name: Build COA AzerothCore Windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup vcpkg
      uses: microsoft/vcpkg-setup@v1
      with:
        vcpkg-commit: 5e4a327ff2f706486d50f14c8440f38c87b10e5b

    - name: Install required libraries
      run: |
        vcpkg install boost:x64-windows mysql:x64-windows openssl:x64-windows bzip2:x64-windows readline:x64-windows
        vcpkg integrate install

    - name: CMake Configure
      run: |
        mkdir build
        cd build
        cmake ../ -G "Visual Studio 17 2022" -A x64 `
        -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
        -DCMAKE_INSTALL_PREFIX="$env:GITHUB_WORKSPACE/dist" `
        -DSCRIPTS=static `
        -DMODULES=static `
        -DTOOLS_BUILD=none `
        -DWITH_WARNINGS=OFF

    - name: Build Release
      run: |
        cd build
        cmake --build . --config Release
        cmake --install .

    - name: Upload compiled binaries
      uses: actions/upload-artifact@v4
      with:
        name: coa-windows-bin
        path: dist/
